services:
    fifty_deg.sylius_cache_plugin.adapters.cache_adapter:
        class: FiftyDeg\SyliusCachePlugin\Adapters\FilesystemCacheAdapter
        arguments:
            $utilities: '@fifty_deg.sylius_cache_plugin.processor.utilities'
            $env: '%kernel.environment%'
            $cacheDir: '%kernel.project_dir%'
            $namespace: 'FiftyDegSyliusCache'
            $defaultTtl: 3600

