app_admin_fifty_deg_cache_index:
    path: /admin/fifty-deg-cache/index/
    methods: [ GET ]
    controller: fifty_deg.sylius_cache_plugin.controller.cache_flusher_controller::indexAction

app_admin_fifty_deg_cache_flusher_ajax:
    path: /admin/fifty-deg-cache/flush/
    methods: [ POST ]
    controller: fifty_deg.sylius_cache_plugin.controller.cache_flusher_controller::flushAction
