sylius_ui:
    events:
        sylius.admin.layout.javascripts:
            blocks:
                fiftydeg_cache_scripts:
                    template: "@FiftyDegSyliusCachePlugin/Admin/Layout/_scripts.html.twig"
                    priority: 10
 
        sylius.shop.layout.javascripts:
            blocks:
                fiftydeg_cache_scripts:
                    template: "@FiftyDegSyliusCachePlugin/Shop/Layout/_scripts.html.twig"
                    priority: 10
