services:
    fifty_deg.sylius_cache_plugin.menu.admin_menu_listener:
        class: FiftyDeg\SyliusCachePlugin\Menu\AdminMainMenuListener
        arguments:
            - '@translator.data_collector'
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addShopSettingsMenu }
