services:
    fifty_deg.sylius_cache_plugin.adapters.cache_adapter:
        class: FiftyDeg\SyliusCachePlugin\Adapters\FilesystemCacheAdapter
        arguments:
            $channelContext: '@sylius.context.channel'
            $localeContext: '@sylius.context.locale'
            $projectDir: '%kernel.project_dir%'
            $namespace: 'FiftyDegSyliusCache'
            $ttl: 3600

