services:

    sylius.twig.extension.template_event:
        class: FiftyDeg\SyliusCachePlugin\Twig\TemplateEventExtension
        arguments:
            - "@Sylius\\Bundle\\UiBundle\\Renderer\\TemplateEventRendererInterface"
            - "@fifty_deg.sylius_cache_plugin.adapters.cache_adapter"
            - "@fifty_deg.sylius_cache_plugin.config_loader.config_loader"
        tags: [ 'twig.extension' ]
